### ISSUE TITLE
GTA: SA - Connected - Issues

### ISSUE THREAD

**Issue by Landimizer** [VortrexFTW/v-essentials#1]
Here are the issues I've found so far.

- Respawning is impossible. After death, you need to reconnect.
- Changing skins doesn't work.
- In an SA server, using the "spawnscreen" resource that is public doesn't properly load during startup.
- Teleporting to a player name sometimes brings you to a different player.

**Comment by BTFighter** [comment]
Would want to bump this as well, specifically the "spawnscreen" resource. I already enabled cvar scripts in my server and it still doesn't work. Using latest steam version.

**Comment by VortrexFTW** [comment]
The SA respawn will need to be handled differently. The script relies on the "OnPedWasted" event, which isn't available on SA. I'll fix this soon. 

The skin and teleport issues are already fixed. I'll check on the spawnscreen resource.

**Comment by BTFighter** [comment]
Just tested commit **11629e3f0eaa5cfc323f49a0790fcb9c132d84bf** and it works great! However, is there a way to remove the wanted levels when you die?

**Comment by VortrexFTW** [comment]
**de731ba74e0380c9cf7f7636543f7c3c33128da0**

Needs tested

**Comment by BTFighter** [comment]
Nope, **de731ba74e0380c9cf7f7636543f7c3c33128da0** doesn't work for me. I can send a video if you want.
