### ISSUE TITLE
Minor bug: Issue with v-time line 7 says 'Weather is not available on this game!'. 

### ISSUE THREAD

**Issue by realdiegopoptart** [VortrexFTW/v-essentials#16]
https://github.com/VortrexFTW/v-essentials/blob/e9b87caa7ac5fa45c3e9c0745d3b90857d34158f/v-time/server.js#L7

```js
        console.warn("Weather is not available on this game!");
        event.preventDefault();
    }
```

**Comment by VortrexFTW** [comment]
Fixed in https://github.com/VortrexFTW/v-essentials/commit/7e7b57ec1c63d775df4ecf909aa5bc7b8c0dc9fe
