### ISSUE TITLE
v-admin and your other resources problem

### ISSUE THREAD

**Issue by Galloux89** [VortrexFTW/v-essentials#2]
hello, there really isn't much information even none on how to use your resources, which creates a big problem because when I enter my nickname or my ip in the config.json by v-admin it doesn't work and crashes the server.. .what do I need to enter for it to work?

**Comment by VortrexFTW** [comment]
The v-admin config.json is not meant to be edited manually, and doesn't accept direct IP's or name's in the array. It uses an object that contains the name, IP, and the admin who added them. Use the makeadmin command in server console with your name to give yourself admin and it'll save the correct format.

**Comment by Galloux89** [comment]
thank you for responding so quickly, it works perfectly now! I think it's one of the best resources I've installed so far, thank you very much for creating it! and thanks again for the help :)
